cabal-version:      3.0
name:               procps-bindings
version:            0.1.0.0
synopsis:           Haskell bindings to the procps library
description:        Haskell bindings to the procps library.
category:           Control, System
license:            BSD-3-Clause
license-file:       LICENSE
author:             Frederick Pringle
maintainer:         freddyjepringle@gmail.com
copyright:          Copyright(c) Frederick Pringle 2025
homepage:           https://github.com/fpringle/hprocps
build-type:         Simple
extra-source-files:
  , cbits/util.h
  , cbits/proctab-handle.h
  , cbits/proc-handle.h
  , cbits/util.c
  , cbits/proctab-handle.c
  , cbits/proc-handle.c

flag pkg-config
  default:     True
  manual:      False
  description: Use @pkg-config@ executable to find the procps C library.

flag debug
  default:     False
  manual:      True
  description: Compile with symbols so we can debug in GDB.

common warnings
  ghc-options: -Wall -Wno-unused-do-bind
  cc-options: -Wno-int-conversion -Wno-implicit-function-declaration
  if flag(debug)
    ghc-options: -g3 -finfo-table-map
    cc-options: -g -ggdb -DDEBUG
    cpp-options: -DDEBUG

common deps
  build-depends:
    , base >= 4 && < 5

common extensions
  default-extensions:
    FlexibleInstances
    LambdaCase
    RecordWildCards
    ScopedTypeVariables
    KindSignatures

library
  import:
      warnings
    , deps
    , extensions
  exposed-modules:
      System.Proc.Bindings
      System.Proc.Bindings.Error
      System.Proc.Bindings.Tab
      System.Proc.Bindings.Tab.Config
  other-modules:
      System.Proc.Bindings.Flags.C
      System.Proc.Bindings.Tab.C
      System.Proc.Bindings.Tab.Internal
      System.Proc.Bindings.C
      System.Proc.Bindings.C.Utils
  hs-source-dirs:   src
  default-language: Haskell2010

  if flag(pkg-config)
    pkgconfig-depends: libprocps >= 3.0 && < 4
  else
    extra-libraries: procps

  include-dirs:     cbits
  includes:         cbits/util.h
                    cbits/proctab-handle.h
                    cbits/proc-handle.h
  install-includes: cbits/util.h
                    cbits/proctab-handle.h
                    cbits/proc-handle.h
  c-sources:        cbits/util.c
                    cbits/proctab-handle.c
                    cbits/proc-handle.c
  build-tool-depends:  hsc2hs:hsc2hs

test-suite procps-bindings-test
  import:
      warnings
    , deps
    , extensions
  default-language: Haskell2010
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  build-tool-depends:
      hspec-discover:hspec-discover
  ghc-options:      -Wno-orphans
  build-depends:
    , procps-bindings
    , QuickCheck
    , hspec
