cabal-version:      3.0
name:               procps-bindings
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Frederick Pringle
maintainer:         freddyjepringle@gmail.com
copyright:          Copyright(c) Frederick Pringle 2025
homepage:           https://github.com/fpringle/hprocps
build-type:         Simple
extra-source-files:
  , cbits/proctab-handle.h
  , cbits/proc-handle.h
  , cbits/proctab-handle.c
  , cbits/proc-handle.c

flag pkg-config
  default:     True
  manual:      False
  description: Use @pkg-config@ executable to find the procps C library.

common warnings
  ghc-options: -g3 -Wall -Wno-unused-do-bind -finfo-table-map
  cc-options: -g -ggdb -Wno-int-conversion -Wno-implicit-function-declaration

common deps
  build-depends:
    , base >= 4
    -- , breakpoint

common extensions
  default-extensions:
    BangPatterns
    DeriveGeneric
    DerivingVia 
    FlexibleContexts
    FlexibleInstances
    GADTs
    InstanceSigs
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    OverloadedStrings
    PackageImports
    RecordWildCards
    ScopedTypeVariables
    TupleSections
    TypeApplications
    ViewPatterns
    RankNTypes
    UndecidableInstances
    KindSignatures
    DataKinds
    StandaloneKindSignatures
    AllowAmbiguousTypes
    DefaultSignatures
    PolyKinds
    TypeFamilies
    ConstraintKinds
    StandaloneDeriving
    Arrows
    TypeOperators

library
  import:
      warnings
    , deps
    , extensions
  exposed-modules:
      System.Proc.Bindings
      System.Proc.Bindings.Error
      System.Proc.Bindings.Tab
      System.Proc.Bindings.Tab.Config
  other-modules:
      System.Proc.Bindings.Flags.C
      System.Proc.Bindings.Tab.C
      System.Proc.Bindings.Tab.Internal
      System.Proc.Bindings.C
      System.Proc.Bindings.C.Utils
      System.Proc.Bindings.Internal
  -- other-extensions:
  hs-source-dirs:   src
  default-language: Haskell2010

  if flag(pkg-config)
    pkgconfig-depends: libprocps >= 3.0 && < 4
  else
    extra-libraries: procps

  include-dirs:     cbits
  includes:         cbits/proctab-handle.h
                    cbits/proc-handle.h
  install-includes: cbits/proctab-handle.h
                    cbits/proc-handle.h
  c-sources:        cbits/proctab-handle.c
                    cbits/proc-handle.c
  build-tool-depends:  hsc2hs:hsc2hs

test-suite procps-bindings-test
  import:
      warnings
    , deps
    , extensions
  default-language: Haskell2010
  -- other-modules:
  -- other-extensions:
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  build-tool-depends:
      hspec-discover:hspec-discover
  ghc-options:      -Wno-orphans
  build-depends:
    , procps-bindings
    , QuickCheck
    , hspec
